# Generated by Django 3.2.4 on 2021-06-14 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('variants', models.TextField(verbose_name='Варианты')),
                ('answers', models.CharField(max_length=100, verbose_name='Ответы')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Голосование',
                'verbose_name_plural': 'Голосования',
            },
        ),
    ]
